"use strict";
module.exports = {
  AleshaWhoSmilesatDeath: require("./AleshaWhoSmilesatDeath"),
  Arcbond: require("./Arcbond"),
  ArchfiendofDepravity: require("./ArchfiendofDepravity"),
  AtarkaWorldRender: require("./AtarkaWorldRender"),
  BrutalHordechief: require("./BrutalHordechief"),
  DaghatartheAdamant: require("./DaghatartheAdamant"),
  DragonscaleGeneral: require("./DragonscaleGeneral"),
  DromokatheEternal: require("./DromokatheEternal"),
  FlamerushRider: require("./FlamerushRider"),
  FlamewakePhoenix: require("./FlamewakePhoenix"),
  JeskaiInfiltrator: require("./JeskaiInfiltrator"),
  KolaghantheStormsFury: require("./KolaghantheStormsFury"),
  MarduShadowspear: require("./MarduShadowspear"),
  MarduStrikeLeader: require("./MarduStrikeLeader"),
  MasteryoftheUnseen: require("./MasteryoftheUnseen"),
  OjutaiSoulofWinter: require("./OjutaiSoulofWinter"),
  RallytheAncestors: require("./RallytheAncestors"),
  SageEyeAvengers: require("./SageEyeAvengers"),
  SandsteppeMastodon: require("./SandsteppeMastodon"),
  ShamanicRevelation: require("./ShamanicRevelation"),
  ShamanoftheGreatHunt: require("./ShamanoftheGreatHunt"),
  ShuYuntheSilentTempest: require("./ShuYuntheSilentTempest"),
  SilumgartheDriftingDeath: require("./SilumgartheDriftingDeath"),
  SoulfireGrandMaster: require("./SoulfireGrandMaster"),
  Soulflayer: require("./Soulflayer"),
  SupplantForm: require("./SupplantForm"),
  TasigurtheGoldenFang: require("./TasigurtheGoldenFang"),
  TemurWarShaman: require("./TemurWarShaman"),
  TorrentElemental: require("./TorrentElemental"),
  WardenoftheFirstTree: require("./WardenoftheFirstTree"),
  Wildcall: require("./Wildcall"),
  YasovaDragonclaw: require("./YasovaDragonclaw")
};
if (window) {if (!window.mtgSets) { window.mtgSets = {}; } window.mtgSets.setPFRF = module.exports;}