"use strict";
module.exports = {
  AjaniVengeant: require("./AjaniVengeant"),
  AncientHellkite: require("./AncientHellkite"),
  AntQueen: require("./AntQueen"),
  BidentofThassa: require("./BidentofThassa"),
  Breaking: require("./Breaking"),
  ColossalWhale: require("./ColossalWhale"),
  DeadbridgeGoliath: require("./DeadbridgeGoliath"),
  DeathbringerRegent: require("./DeathbringerRegent"),
  DictateoftheTwinGods: require("./DictateoftheTwinGods"),
  DragonThroneofTarkir: require("./DragonThroneofTarkir"),
  EarwigSquad: require("./EarwigSquad"),
  Entering: require("./Entering"),
  FigureofDestiny: require("./FigureofDestiny"),
  GarruksHorde: require("./GarruksHorde"),
  InGarruksWake: require("./InGarruksWake"),
  JoragaWarcaller: require("./JoragaWarcaller"),
  KnightofNewAlara: require("./KnightofNewAlara"),
  LordofShatterskullPass: require("./LordofShatterskullPass"),
  LudevicsAbomination: require("./LudevicsAbomination"),
  LudevicsTestSubject: require("./LudevicsTestSubject"),
  MondronenShaman: require("./MondronenShaman"),
  ObeliskofAlara: require("./ObeliskofAlara"),
  PhyrexianMetamorph: require("./PhyrexianMetamorph"),
  RestorationAngel: require("./RestorationAngel"),
  SandsteppeMastodon: require("./SandsteppeMastodon"),
  SkarrgGoliath: require("./SkarrgGoliath"),
  StaffofNin: require("./StaffofNin"),
  SteelHellkite: require("./SteelHellkite"),
  ThopterAssembly: require("./ThopterAssembly"),
  TovolarsMagehunter: require("./TovolarsMagehunter"),
  Tromokratis: require("./Tromokratis"),
  ValakuttheMoltenPinnacle: require("./ValakuttheMoltenPinnacle"),
  VexingShusher: require("./VexingShusher")
};
if (window) {if (!window.mtgSets) { window.mtgSets = {}; } window.mtgSets.setpLPA = module.exports;}