var Events = {
	BEGIN_STEP: "BEGIN_STEP",
	CREATURE_ENTERED_BATTLEFIELD: "CREATURE_ENTERED_BATTLEFIELD",
	PERMANENT_UNTAPPED: "PERMANENT_UNTAPPED",
	PERMANENT_TAPPED: "PERMANENT_TAPPED"
};

module.exports = Events;
