var Inputs = {
	KEEP_HAND: "KEEP_HAND",
	MULLIGAN_HAND: "MULLIGAN_HAND",
	PASS_PRIORITY: "PASS_PRIORITY",
	CAST_SPELL: "CAST_SPELL",
	ACTIVATE_ABILITY: "ACTIVATE_ABILITY",
	PLACE_TRIGGER_ON_STACK: "PLACE_TRIGGER_ON_STACK",
	PLAY_LAND: "PLAY_LAND",
	CONCEDE: "CONCEDE"
};

module.exports = Inputs;
