var Inputs = {
	KEEP_HAND: "KEEP_HAND",
	MULLIGAN_HAND: "MULLIGAN_HAND",
	PASS_PRIORITY: "PASS_PRIORITY",
	CAST_SPELL: "CAST_SPELL",
	ACTIVATE_ABILITY: "ACTIVATE_ABILITY",
	PLACE_TRIGGER_ON_STACK: "PLACE_TRIGGER_ON_STACK",
	PLACE_COPY_ON_STACK: "PLACE_COPY_ON_STACK",

	// Special actions
	PLAY_LAND: "PLAY_LAND",
	TURN_CREATURE_FACE_UP: "TURN_CREATURE_FACE_UP",
	STOP_TRIGGER: "STOP_TRIGGER", // CR 115.2c (See: Glass Asp, Quenchable Fire)
	IGNORE_EFFECT: "IGNORE_EFFECT", // CR 115.2d (See: Leonin Arbiter)
	SUSPEND_CARD: "SUSPEND_CARD",

	CONCEDE: "CONCEDE"
};

module.exports = Inputs;
