"use strict";
module.exports = {
  AinokTracker: require("./AinokTracker"),
  AltaroftheBrood: require("./AltaroftheBrood"),
  ArashinWarBeast: require("./ArashinWarBeast"),
  ArcLightning: require("./ArcLightning"),
  BribersPurse: require("./BribersPurse"),
  DebilitatingInjury: require("./DebilitatingInjury"),
  DragonscaleBoon: require("./DragonscaleBoon"),
  FierceInvocation: require("./FierceInvocation"),
  FormlessNurturing: require("./FormlessNurturing"),
  GhostfireBlade: require("./GhostfireBlade"),
  GrimHaruspex: require("./GrimHaruspex"),
  HewedStoneRetainers: require("./HewedStoneRetainers"),
  JeeringInstigator: require("./JeeringInstigator"),
  JeskaiInfiltrator: require("./JeskaiInfiltrator"),
  MasteryoftheUnseen: require("./MasteryoftheUnseen"),
  MysticoftheHiddenWay: require("./MysticoftheHiddenWay"),
  RealityShift: require("./RealityShift"),
  RuthlessRipper: require("./RuthlessRipper"),
  SmitetheMonstrous: require("./SmitetheMonstrous"),
  SoulSummons: require("./SoulSummons"),
  SultaiEmissary: require("./SultaiEmissary"),
  UginsConstruct: require("./UginsConstruct"),
  UgintheSpiritDragon: require("./UgintheSpiritDragon"),
  WatcheroftheRoost: require("./WatcheroftheRoost"),
  Wildcall: require("./Wildcall"),
  WriteintoBeing: require("./WriteintoBeing")
};
if (window) {if (!window.mtgSets) { window.mtgSets = {}; } window.mtgSets.setFRF_UGIN = module.exports;}