const Events = {
	BEGIN_STEP: "BEGIN_STEP",
	CREATURE_ENTERED_BATTLEFIELD: "CREATURE_ENTERED_BATTLEFIELD",
	PERMANENT_UNTAPPED: "PERMANENT_UNTAPPED",
	PERMANENT_TAPPED: "PERMANENT_TAPPED",
	SPELL_ANNOUNCED: "SPELL_ANNOUNCED",
	SPELL_CAST: "SPELL_CAST",
	ABILITY_ACTIVATED: "ABILITY_ACTIVATED",
};

module.exports = Events;
