var Inputs = {
	KEEP_HAND: "KEEP_HAND",
	MULLIGAN_HAND: "MULLIGAN_HAND",
	PASS_PRIORITY: "PASS_PRIORITY",

	//////////////////////////////////
	// Steps for casting spells
	ANNOUNCE_SPELL: "ANNOUNCE_SPELL",						// ALL
	ANNOUNCE_ABILITY: "ANNOUNCE_ABILITY",
	CHOOSE_MODES: "CHOOSE_MODES",							// CRAZY
	CHOOSE_TARGETS: "CHOOSE_TARGETS",						// TEENS
	DISTRIBUTE_PARAMETERS: "DISTRIBUTE_PARAMETERS",			// HAVE
	/* Omitted: Calculate total cost */						// TRIED
	ACTIVATE_MANA_ABILITY: "ACTIVATE_MANA_ABILITY",			// MAGIC
	PAY_COST: "PAY_COSTS",									// PILLS
	ABORT_SPELLCAST: "ABORT_SPELLCAST",
	ABORT_ABILITY_ACTIVATION: "ABORT_ABILITY_ACTIVATION",

	PLACE_TRIGGER_ON_STACK: "PLACE_TRIGGER_ON_STACK",
	PLACE_COPY_ON_STACK: "PLACE_COPY_ON_STACK",

	//////////////////////////////////
	// Special actions
	PLAY_LAND: "PLAY_LAND",
	TURN_CREATURE_FACE_UP: "TURN_CREATURE_FACE_UP",
	STOP_TRIGGER: "STOP_TRIGGER", 	// CR 115.2c (See: Glass Asp, Quenchable Fire)
	IGNORE_EFFECT: "IGNORE_EFFECT", // CR 115.2d (See: Leonin Arbiter)
	SUSPEND_CARD: "SUSPEND_CARD",

	CONCEDE: "CONCEDE"
};

module.exports = Inputs;
