var Outputs = {
	NEW_GAME_TIME: "NEW_GAME_TIME",
	PRIORITY_CHANGED: "PRIORITY_CHANGED",
	PERMANENT_ENTERED_BATTLEFIELD: "PERMANENT_ENTERED_BATTLEFIELD",
	OBJECT_PLACED_ON_STACK: "OBJECT_PLACED_ON_STACK",
	PERMANENT_UNTAPPED: "PERMANENT_UNTAPPED",
	PERMANENT_TAPPED: "PERMANENT_TAPPED"
};

module.exports = Outputs;
