const Constants = {
  steps: {
    UNTAP: 0,
    UPKEEP: 1,
    DRAW: 2,
    MAIN1: 3,
    BEGIN_COMBAT: 4,
    DECLARE_ATTACKERS: 5,
    DECLARE_BLOCKERS: 6,
    COMBAT_DAMAGE: 7,
    END_COMBAT: 8,
    MAIN2: 9,
    END: 10,
    CLEANUP: 11,
  },

  tapStates: {
    UNTAPPED: 'UNTAPPED',
    TAPPED: 'TAPPED',
  },

  flipStates: {
    NORMAL: 'NORMAL',
    FLIPPED: 'FLIPPED',
  },

  transformState: {
    NORMAL: 'NORMAL',
    TRANSFORMED: 'TRANSFORMED',
  },

  faceState: {
    FACEUP: 'FACEUP',
    FACEDOWN: 'FACEDOWN',
  },

  zoneTypes: {
    PUBLIC: 'PUBLIC',
    HIDDEN: 'HIDDEN',
  },

  zoneOwnership: {
    PLAYER: 'PLAYER',
    SHARED: 'SHARED',
  },

  zoneIdentifiers: {
    BATTLEFIELD: 'BATTLEFIELD',
    HAND: 'HAND',
    EXILE: 'EXILE',
    COMMAND: 'COMMAND',
    GRAVEYARD: 'GRAVEYARD',
    LIBRARY: 'LIBRARY',
    STACK: 'STACK',
  },

  cardSuperTypes: {
    LEGENDARY: 'LEGENDARY',
    BASIC: 'BASIC',
    WORLD: 'WORLD',
    SNOW: 'SNOW',
    ONGOING: 'ONGOING',
    ELITE: 'ELITE',
    HOST: 'HOST',
  },

  cardTypes: {
    ARTIFACT: 'ARTIFACT',
    CONSPIRACY: 'CONSPIRACY',
    CREATURE: 'CREATURE',
    ENCHANTMENT: 'ENCHANTMENT',
    INSTANT: 'INSTANT',
    LAND: 'LAND',
    PHENOMENON: 'PHENOMENON',
    PLANE: 'PLANE',
    PLANESWALKER: 'PLANESWALKER',
    SCHEME: 'SCHEME',
    SORCERY: 'SORCERY',
    TRIBAL: 'TRIBAL',
    VANGUARD: 'VANGUARD',
  },

  colors: {
    WHITE: 'WHITE',
    BLUE: 'BLUE',
    BLACK: 'BLACK',
    RED: 'RED',
    GREEN: 'GREEN',
  },

  manaTypes: {
    WHITE: 'WHITE',
    BLUE: 'BLUE',
    BLACK: 'BLACK',
    RED: 'RED',
    GREEN: 'GREEN',
    COLORLESS: 'COLORLESS',
  },

  costs: {
    GENERIC: 'GENERIC',
    COLORLESS: 'COLORLESS',

    WHITE: 'WHITE',
    BLUE: 'BLUE',
    BLACK: 'BLACK',
    RED: 'RED',
    GREEN: 'GREEN',

    WHITE2: 'WHITE2',
    BLUE2: 'BLUE2',
    BLACK2: 'BLACK2',
    RED2: 'RED2',
    GREEN2: 'GREEN2',

    PHYREXIAN: 'PHYREXIAN',
    WHITEPHYREXIAN: 'WHITEPHYREXIAN',
    BLUEPHYREXIAN: 'BLUEPHYREXIAN',
    BLACKPHYREXIAN: 'BLACKPHYREXIAN',
    REDPHYREXIAN: 'REDPHYREXIAN',
    GREENPHYREXIAN: 'GREENPHYREXIAN',

    X: 'X',
    Y: 'Y',
    Z: 'Z',
    SNOW: 'SNOW',
    TAP: 'TAP',
    UNTAP: 'UNTAP',
    SACRIFICE: 'SACRIFICE',
    SPECIAL_COST: 'SPECIAL_COST',

    GOLGARI: 'GOLGARI',
    RAKDOS: 'RAKDOS',
    SIMIC: 'SIMIC',
    SELESNYA: 'SELESNYA',
    GRUUL: 'GRUUL',
    BOROS: 'BOROS',
    DIMIR: 'DIMIR',
    IZZET: 'IZZET',
    ORZHOV: 'ORZHOV',
    AZORIUS: 'AZORIUS',
  },

  costTokens: {
    'C': 'COLORLESS',
    'W': 'WHITE',
    'U': 'BLUE',
    'B': 'BLACK',
    'R': 'RED',
    'G': 'GREEN',
    '2/W': 'WHITE2',
    '2/U': 'BLUE2',
    '2/B': 'BLACK2',
    '2/R': 'RED2',
    '2/G': 'GREEN2',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'T': 'TAP',
    'Q': 'UNTAP',
    'W/U': 'AZORIUS',
    'W/B': 'ORZHOV',
    'B/R': 'RAKDOS',
    'B/G': 'GOLGARI',
    'U/B': 'DIMIR',
    'U/R': 'IZZET',
    'R/G': 'GRUUL',
    'R/W': 'BOROS',
    'G/W': 'SELESNYA',
    'G/U': 'SIMIC',
    'P': 'PHYREXIAN',
    'W/P': 'WHITEPHYREXIAN',
    'U/P': 'BLUEPHYREXIAN',
    'B/P': 'BLACKPHYREXIAN',
    'R/P': 'REDPHYREXIAN',
    'G/P': 'GREENPHYREXIAN',
    'S': 'SNOW',
  },

  keywordAbilities: {
    DEATHTOUCH: 'DEATHTOUCH',
    DEFENDER: 'DEFENDER',
    DOUBLE_STRIKE: 'DOUBLE_STRIKE',
    ENCHANT: 'ENCHANT',
    EQUIP: 'EQUIP',
    FIRST_STRIKE: 'FIRST_STRIKE',
    FLASH: 'FLASH',
    FLYING: 'FLYING',
    HASTE: 'HASTE',
    HEXPROOF: 'HEXPROOF',
    INDESTRUCTIBLE: 'INDESTRUCTIBLE',
    INTIMIDATE: 'INTIMIDATE',
    LANDWALK: 'LANDWALK',
    LIFELINK: 'LIFELINK',
    PROTECTION: 'PROTECTION',
    REACH: 'REACH',
    SHROUD: 'SHROUD',
    TRAMPLE: 'TRAMPLE',
    VIGILANCE: 'VIGILANCE',

    INFECT: 'INFECT',
  },

  counterTypes: {
    PLUS_ONE_PLUS_ONE: 'PLUS_ONE_PLUS_ONE',
    MINUS_ONE_MINUS_ONE: 'MINUS_ONE_MINUS_ONE',
    LOYALTY: 'LOYALTY',
    AGE: 'AGE',
    TIME: 'TIME',
  },
};

module.exports = Constants;
