"use strict";
module.exports = {
  AirElemental: require("./AirElemental"),
  BloodhunterBat: require("./BloodhunterBat"),
  CertainDeath: require("./CertainDeath"),
  CoralMerfolk: require("./CoralMerfolk"),
  DivineVerdict: require("./DivineVerdict"),
  DragUnder: require("./DragUnder"),
  FalkenrathReaver: require("./FalkenrathReaver"),
  GarruksHorde: require("./GarruksHorde"),
  GlorySeeker: require("./GlorySeeker"),
  Inspiration: require("./Inspiration"),
  Nightmare: require("./Nightmare"),
  Oakenform: require("./Oakenform"),
  RabidBite: require("./RabidBite"),
  RaiseDead: require("./RaiseDead"),
  Rootwalla: require("./Rootwalla"),
  SengirVampire: require("./SengirVampire"),
  SerraAngel: require("./SerraAngel"),
  ShivanDragon: require("./ShivanDragon"),
  SleepParalysis: require("./SleepParalysis"),
  SphinxofMagosi: require("./SphinxofMagosi"),
  StalkingTiger: require("./StalkingTiger"),
  StampedingRhino: require("./StampedingRhino"),
  StandingTroops: require("./StandingTroops"),
  StealerofSecrets: require("./StealerofSecrets"),
  StormfrontPegasus: require("./StormfrontPegasus"),
  ThunderingGiant: require("./ThunderingGiant"),
  TricksoftheTrade: require("./TricksoftheTrade"),
  UntamedHunger: require("./UntamedHunger"),
  VictorysHerald: require("./VictorysHerald"),
  WingSnare: require("./WingSnare")
};
if (window) {if (!window.mtgSets) { window.mtgSets = {}; } window.mtgSets.setW17 = module.exports;}