"use strict";
module.exports = {
  Ashnod: require("./Ashnod"),
  Barrin: require("./Barrin"),
  Crovax: require("./Crovax"),
  Eladamri: require("./Eladamri"),
  Ertai: require("./Ertai"),
  Gerrard: require("./Gerrard"),
  Gix: require("./Gix"),
  GrevenilVec: require("./GrevenilVec"),
  Hanna: require("./Hanna"),
  Karn: require("./Karn"),
  Lyna: require("./Lyna"),
  Maraxus: require("./Maraxus"),
  Mirri: require("./Mirri"),
  Mishra: require("./Mishra"),
  Multani: require("./Multani"),
  Oracle: require("./Oracle"),
  Orim: require("./Orim"),
  Rofellos: require("./Rofellos"),
  Selenia: require("./Selenia"),
  Serra: require("./Serra"),
  SidarKondo: require("./SidarKondo"),
  Sisay: require("./Sisay"),
  SliverQueenBroodMother: require("./SliverQueenBroodMother"),
  Squee: require("./Squee"),
  Starke: require("./Starke"),
  Tahngarth: require("./Tahngarth"),
  Takara: require("./Takara"),
  Tawnos: require("./Tawnos"),
  Titania: require("./Titania"),
  Urza: require("./Urza"),
  Volrath: require("./Volrath"),
  Xantcha: require("./Xantcha")
};
if (window) {if (!window.mtgSets) { window.mtgSets = {}; } window.mtgSets.setPVAN = module.exports;}