"use strict";
module.exports = {
  BurrentonForgeTender: require("./BurrentonForgeTender"),
  CavesofKoilos: require("./CavesofKoilos"),
  CityofBrass: require("./CityofBrass"),
  Dismember: require("./Dismember"),
  Duress: require("./Duress"),
  ElspethKnightErrant: require("./ElspethKnightErrant"),
  GhostQuarter: require("./GhostQuarter"),
  HonorofthePure: require("./HonorofthePure"),
  InquisitionofKozilek: require("./InquisitionofKozilek"),
  IntangibleVirtue: require("./IntangibleVirtue"),
  IsolatedChapel: require("./IsolatedChapel"),
  KatakiWarsWage: require("./KatakiWarsWage"),
  LingeringSouls: require("./LingeringSouls"),
  PathtoExile: require("./PathtoExile"),
  Plains: require("./Plains"),
  RaisetheAlarm: require("./RaisetheAlarm"),
  RelicofProgenitus: require("./RelicofProgenitus"),
  ShrineofLoyalLegions: require("./ShrineofLoyalLegions"),
  SoulWarden: require("./SoulWarden"),
  SpectralProcession: require("./SpectralProcession"),
  Swamp: require("./Swamp"),
  SwordofFeastandFamine: require("./SwordofFeastandFamine"),
  TidehollowSculler: require("./TidehollowSculler"),
  VaultoftheArchangel: require("./VaultoftheArchangel"),
  WindbriskHeights: require("./WindbriskHeights"),
  ZealousPersecution: require("./ZealousPersecution")
};
if (window) {if (!window.mtgSets) { window.mtgSets = {}; } window.mtgSets.setMD1 = module.exports;}