const Outputs = {
  NEW_GAME_TIME: "NEW_GAME_TIME",
  PRIORITY_CHANGED: "PRIORITY_CHANGED",
  OBJECT_ENTERED_ZONE: "OBJECT_ENTERED_ZONE",
  PERMANENT_UNTAPPED: "PERMANENT_UNTAPPED",
  PERMANENT_TAPPED: "PERMANENT_TAPPED"
};

module.exports = Outputs;
